doc/changes/changelog.md
doc/changes/changes_0.2.1.md
doc/changes/changes_0.2.2.md
exasol/connections.py
pyproject.toml
test/unit/test_connections.py
version.py

Fixes the schema and empty config value bugs

---

doc/changes/changelog.md
doc/changes/changes_0.2.3.md
exasol/connections.py
pyproject.toml
version.py

Updates the connections module

---

doc/changes/changelog.md
doc/changes/changes_0.2.4.md
exasol/connections.py
exasol/utils.py
pyproject.toml
test/unit/test_utils.py
version.py

File search utility

---

exasol/bfs_utils.py
exasol/cloud_storage.py
exasol/github.py
poetry.lock
pyproject.toml
test/unit/test_bfs_utils.py
test/unit/test_github.py

Closes https://github.com/exasol/data-science-sandbox/issues/37

Move setup code from cloud-storage notebooks to lib

---

doc/changes/changes_0.2.6.md
exasol/itde_manager.py
test/integration/test_itde_manager.py

Improves ITDE manager

---

doc/changes/changes_0.2.6.md
exasol/language_container_activation.py
exasol/sagemaker_extension_wrapper.py
exasol/transformers_extension_wrapper.py
poetry.lock
pyproject.toml
test/unit/test_language_container_activation.py

Changed get_activation_sql

---

doc/changes/changes_0.2.6.md
exasol/itde_manager.py
test/integration/test_itde_manager_in_docker_container.py

#78: Added removal of the current container from docker network of the ITDE

---

doc/changes/changelog.md
doc/changes/changes_0.2.8.md
poetry.lock
pyproject.toml
version.py

Updating the extension dependencies

---

doc/changes/changes_0.2.9.md
exasol/nb_connector/extension_wrapper_common.py
test/unit/test_extension_wrapper_common.py

#99: Setting correct parameters in a BFS connection object

---

exasol/nb_connector/extension_wrapper_common.py
exasol/nb_connector/sagemaker_extension_wrapper.py
exasol/nb_connector/transformers_extension_wrapper.py

#112 Handle missing config elements correctly

---

exasol/nb_connector/extension_wrapper_common.py
exasol/nb_connector/sagemaker_extension_wrapper.py
exasol/nb_connector/transformers_extension_wrapper.py

#114 Calling the language container deployer correctly

---

exasol/nb_connector/extension_wrapper_common.py
test/unit/test_extension_wrapper_common.py

#119 Fixed the json bugs in the bucketfs connection object

---

.github/workflows/checks.yml
doc/changes/unreleased.md
exasol/nb_connector/connections.py
poetry.lock
pyproject.toml
test/integration/test_itde_manager_in_docker_container.py
test/unit/test_connections.py

#123 Added Ibis connection

---

doc/changes/changes_0.3.0.md
exasol/nb_connector/ai_lab_config.py
exasol/nb_connector/extension_wrapper_common.py
exasol/nb_connector/sagemaker_extension_wrapper.py
exasol/nb_connector/transformers_extension_wrapper.py
test/integration/test_sagemaker_extension_wrapper.py
test/integration/test_transformers_extension_wrapper.py
test/unit/test_extension_wrapper_common.py
test/utils/integration_test_utils.py

#133 override language def and use internal bfs host/port

---

doc/changes/changes_0.3.0.md
exasol/nb_connector/slct_manager.py

#125 pinned script languages release to tag 8.2.0

---

.github/workflows/build-and-publish.yml
.github/workflows/check-release-tag.yml
.github/workflows/checks.yml
.github/workflows/gh-pages.yml
.github/workflows/report.yml
doc/changes/unreleased.md
poetry.lock

 #146: Fixed vulnerabilities by updating dependencies

---

.github/workflows/checks.yml
exasol/nb_connector/itde_manager.py
test/unit/test_itde_manager.py

Fix DB version not taken into account

---

doc/changes/changelog.md
doc/changes/changes_0.4.2.md
doc/changes/unreleased.md
exasol/nb_connector/bfs_utils.py
pyproject.toml
test/integration/test_cloud_storage.py
test/unit/test_bfs_utils.py
version.py

Proper fix of `bfs_utils.put_file`

---

doc/changes/unreleased.md
exasol/nb_connector/extension_wrapper_common.py

#173: Added an option to upload an SLC from file

---

doc/changes/unreleased.md
exasol/nb_connector/ai_lab_config.py
exasol/nb_connector/text_ai_extension_wrapper.py
test/integration/test_text_ai_extension_wrapper.py

#175: Add function to download and decrypt Text-AI pre-release
